config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cards#index'

  resources :cards, only: [:show] do |card|
    collection do
      get '/search', to: 'cards#search'
    end
  end

  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ActiveRecord::Base
  
  validates_presence_of :title, :snippet, :content

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    Card.where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :password, :name
  validates_uniqueness_of :email

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def require_user
    redirect_to login_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show]

  def index
    @cards = Card.all
  end

  def show
  end

  def search
    @results = Card.search_by_title(params[:search_term])
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "You are signed in. Enjoy!"
    else
      flash[:error] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You are signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to sign_in_path
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card_preview.html.haml
%section.cd-card{ tabindex: '0', 'data-id': card.id}
  %h2 
    = link_to card.title, card_path(card)
  %p= card.snippet
  .cd-bottom-line
    %button.cd-card-btn.cd-select-card Start
    %button.cd-card-btn.cd-like-card
      %i.cd-card-icon.fa.fa-bookmark-o
    %button.cd-card-btn.cd-favorite-card
      %i.cd-card-icon.fa.fa-heart-o
    %button.cd-card-btn.cd-like-card
      %i.cd-card-icon.fa.fa-thumbs-o-up.selected
    %button.cd-card-btn.cd-rating-card
      %i.cd-card-icon.fa.fa-star-o
      %i.cd-card-icon.fa.fa-star-o
      %i.cd-card-icon.fa.fa-star-o
      %i.cd-card-icon.fa.fa-star-o
      %i.cd-card-icon.fa.fa-star-o

app/views/cards/index.html.haml
%section.container.cd-cards-container
  - @cards.each do |card|
    = render 'cards/card_preview', card: card

app/views/cards/search.html.haml
.cards-container
  - @results.each do |card|
    = render 'cards/card_preview', card: card

app/views/cards/show.html.haml
%article.container
  %h1= @card.title
  %p= @card.snippet
  %section.show-more
    %h2 Create this card

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCardApp</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/2793880438.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <main id="mainContent">
      <%= render 'shared/ad_top' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_ad_top.html.haml
.ad-top
  %img{ src: 'http://placehold.it/800X100'}

app/views/shared/_header.html.haml
%header.main-header
  %section.container.cf
    %nav.header-nav
      %ul.main-menu
        %li= link_to "Home", root_path
        %li.has-menu
          %a Categories
          %ul.secondary-menu
            %li= link_to "Anniversary"
            %li
              %a Birthday
            %li= link_to "Congratulations"
            %li
              %a Holiday
        %li= link_to "Favorites"
        %li= link_to "Settings"
      .right-nav-bar
        %input.header-search{ type: 'search', placeholder: 'bonne nuit' }
        %button.btn.btn-search{ type: 'search' } Search
        %a.login= link_to "Log in", login_path